version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./dist:/app/dist
      - ./server:/app/server
      - ./www:/app/www
  redis:
    image: redis:3
    ports:
      - '6379:6379'
